### ISSUE TITLE
DOC101

### ISSUE THREAD

**Issue by sjeknic** [FlukeAndFeather/jese4sci-DOC#1]
1. - Readme and quickstart: Lowest level, for people who just want to run the code as is and interact with it in a minimal way. They need to know how to install the software and the basic functions/commands to use.
   - API: This is for people who are working with the code directly. People who want to use your code in their own work will need to know how each of the functions work, the parameters passed, and what to expect in return. 
   - Comments: Highest level, for people who are actually reading the code. If someone has gone all the way into the code to see what is specifically happening, then they are likely an advanced user. Instead of trying to parse the function of each individual line, the comments serve to make the code more human readable. 

2. I owe a lot of my graduate school work to this code built by a former graduate student in the lab: [https://github.com/braysia/CellTK](https://github.com/braysia/CellTK). The way to learn to use it was to have that student explain it to you and then hands on trying. It was challenging, because often times you couldn't tell if a weird result was because you were doing something wrong or because there was a bug in the code. Errors were common, but it was often a black box as to how they got raised. The README wasn't really useful, and most people in the lab wanted to use this code for their own purposes, which required a fair amount of headache to understand because no API existed and the comments are sparse (at best). 

3. Unstructured scripts are difficult to document because there aren't really separate functions or modules that are immediately apparent in the script. Therefore you can't really write an API, as there isn't usually a higher level way of interacting with the code. A README is possible, and useful for anyone just looking to run the script. But anyone who wants to actually understand the code or adapt it will need to read the code and hope it is well commented.

**Comment by mcgoodman** [comment]
Great answers Stevan! The only comment I have is on terminology - "high level" in programming is usually meant to indicate that something is abstracted - e.g. R is "higher level" than C, which is higher level than assembly or binary. So, the README is the highest level, and line comments are the lowest level. Feel free to close this issue once you've read this.

**Comment by sjeknic** [comment]
Gotcha, thanks for the clarification!
