### ISSUE TITLE
DOC101

### ISSUE THREAD

**Issue by joydoong** [FlukeAndFeather/jese4sci-DOC#10]
1. Order the following types of documentation from lowest- to highest-level. Briefly describe who the documentation is for and how they would use it.

    README and quickstart guide: someone just starting out using your code will read it for some basic usage and find direction to additional information
    API: someone using your code that needs more detail for specific parts of the code/package for usage that's beyond the basics
    Comments: someone who may want to edit your code for their own purposes or improve the code, they would use it to understand the source

2. Think of a time you used someone else's code. How did you learn to use it? What types of documentation would have helped?
I learned by reading the source. I would have appreciated some text explaining the steps that were taken in the scripts. 

3. The code that accompanies scientific articles is often one long script (i.e., "spaghetti code"; see MOD101 for more details). What challenges do long, unstructured scripts present to writing effective documentation?
Lack of structure makes it difficult to organize documentation beyond scattered comments -> not hierarchical

**Comment by mcgoodman** [comment]
Great answers Joy!
