### ISSUE TITLE
DOC101

### ISSUE THREAD

**Issue by ggsun** [FlukeAndFeather/jese4sci-DOC#11]
> 1. Order the following types of documentation from lowest- to highest-level. Briefly describe who the documentation is for and how they would use it.
> - API
> - README and quickstart guide
> - Comments

(lowest) Comments - API - README and quickstart guide (highest)

- Comments: Code comments are for people (including yourself) who will read through your source code, and should be written in a way that makes them easier to understand it.
- API: API documentation is to help people that use a certain part of your codebase (a function, class) understand what the required inputs, outputs, potential errors etc. are for the specific module.
- README and quickstart guide: These documents are to help people who are using your software for the first time to get set up with the software and to help them understand the higher level functions of the software. The quickstart guide will help these users quickly run an example analysis using the software.

> 2. Think of a time you used someone else's code. How did you learn to use it? What types of documentation would have helped?

We have an ongoing software project in our lab that was started by a group of graduate students that left our lab before I joined it. Naturally, I had to read through a lot of the legacy code that were left by these group of students to understand the work they had done and identify what needs to be improved. Many times I had to ask a senior graduate student for help when I couldn't use the codebase properly, since much of the knowledge was "verbally" transferred from student to student without being properly documented. I think the codebase was well-documented in terms of helping people who want to simply run the software, but what was lacking was documentation for future developers like me who would want to expand and improve upon the codebase.

> 3. The code that accompanies scientific articles is often one long script (i.e., "spaghetti code"; see MOD101 for more details). What challenges do long, unstructured scripts present to writing effective documentation?

It becomes much more difficult to divide up the software into modules with defined APIs. Without this modular structure it would be very difficult to document the software in terms of function arguments, outputs, etc. that are standard for documentation.

**Comment by mcgoodman** [comment]
Really great answers Gwanggyu! Your answer to the second question is great because it highlights how the different forms of documentations are really targeted at different audiences, and you need documentation at every level.
