### ISSUE TITLE
DOC101

### ISSUE THREAD

**Issue by kathyle9** [FlukeAndFeather/jese4sci-DOC#13]
1)
Comments: This is for people who are building, modifying, or maintaining the source code. Comments help make the structure and reasoning behind the code understandable to others. 
API: This if for people who have started using your code and need to figure out how to use certain functions. Knowing what the functions do, what their inputs are, and what their outputs are will help them apply your code to their problem of interest.
README and quickstart guide: This is for people who are unfamiliar with your code but want to use it for the first time. The README explains the purpose of the code, what it generally does, and the quickstart guide generally walks the user through the basic setup and typical application of the code.

2) 
I learned how to use PyRosetta, a python-based macromolecular modeling software suite. What really helped was "workshops" or "demos" written by people who wrote the code or use it regularly. This helped me learn the technical aspects of using the code (functions, inputs, outputs, etc.) but also what problems it can be applied to and the limitations. Once I started writing my own scripts, the documentation page was the most helpful because I could search for functions that I need and see their namespaces.

3) 
Long, unstructured scripts usually aren't modular, making it much harder to follow the code. This might make it difficult for others to believe/interpret your results. It is also much harder to reuse parts of the code in other scripts, or apply to different data. In addition, spaghetti code tends to rely on many comments to explain the code, which is not as effective as writing modular code.

**Comment by mcgoodman** [comment]
Great answers Kathy!
