### ISSUE TITLE
DOC102

### ISSUE THREAD

**Issue by tomjhandley** [FlukeAndFeather/jese4sci-DOC#14]
1. ggplot2 README: https://cran.r-project.org/web/packages/ggplot2/readme/README.html

Why should I use it?
- "ggplot2 is a system for declaratively creating graphics, based on The Grammar of Graphics. You provide the data, tell ggplot2 how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details."

How do I use it?
- Cheatsheet to get started
-  https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf

How do I get it?
- Installation
# The easiest way to get ggplot2 is to install the whole tidyverse:
install.packages("tidyverse")

# Alternatively, install just ggplot2:
install.packages("ggplot2")

# Or the development version from GitHub:
# install.packages("devtools")
devtools::install_github("tidyverse/ggplot2")

2. https://github.com/tomjhandley/simplerc

**Comment by mcgoodman** [comment]
Looks great Tom!
