### ISSUE TITLE
DOC102

### ISSUE THREAD

**Issue by sjeknic** [FlukeAndFeather/jese4sci-DOC#2]
1.  I'll use the README for the dbscan package that was linked in the question. I don't really use R for my research at all, but I have used dbscan and hdbscan as implemented in Python ([https://hdbscan.readthedocs.io/en/latest/](https://hdbscan.readthedocs.io/en/latest/)) so I think this README is still relevant to me. 
    I think the README does a good job of providing a high level description and how to install the package. However, I think the usage of the package is not very clear. The examples shown are simple, which is fine, but there are no extra details. For example, the outputs are shown, but there is no description of what those outputs include. The outputs themselves are clearly more than just a vector, but there is no further information. For some of the functions the README adds a `plot` function, but those plots are not shown, so I don't know what they should look like. There is also no information about the structure the dataset should be in to use the package (unless you happen to be familiar with the "iris" dataset).
    It is a README and supposed to be high level, but I don't think that based on the README I would be able to implement the package for my own data. 

2. https://github.com/sjeknic/simplerc

**Comment by mcgoodman** [comment]
Totally agree with your assessment of the `dbscan` README, and your `simplerc` README looks great!
