### ISSUE TITLE
DOC101

### ISSUE THREAD

**Issue by gpreising** [FlukeAndFeather/jese4sci-DOC#3]
Q1:
If high = closest to human communication and low = really in the weeds of the code:

a. **Comments** - comments are the lowest level type of documentation since they are interspersed throughout the source code. This type of documentation is useful for people who are trying to debug something or adapt part of your code for something else; these people want to understand exactly how the code works.
b. **API** - I think this would be considered a mid-level form of documentation because you would just enter ?function() in the console to see how specific components of the code work from an implementation-level. This type of documentation is for people looking to take advantage of different function arguments that aren't defaults.
c. 1. **README and quickstart guide** - this is the highest level of documentation because the README is generally what people first learning about your software will read first. This kind of documentation is for people looking to run a similar analysis as quickly as possible without getting into the weeds of your software. 

Q2: Having a tutorial with example data is really really useful and arguably necessary if you're developing tools. Luckily, most of the packages I've had to learn have included an example workflow that I could just reformat my data to match their input files. If I had to figure out a bioinformatics package without any examples, I imagine it would be very tough to learn.

Q3: I think having one long script can be useful at times since it simplifies the number of things someone aiming to replicate the study has to run. However, I can also see how having one long script can be harder to understand, since you have to search through it to find specific parts of analyses and at that point you're mostly relying on comments in the code to guide you. As a result, this increases the cognitive load for the reader.

**Comment by mcgoodman** [comment]
Great answers Gabe!
